// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: establishments.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEstablishment = `-- name: CreateEstablishment :one
INSERT INTO establishments (
    name,
    slug,
    types,
    email,
    website,
    timezone,
    phones,
    address,
    location,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    ST_SetSRID(ST_MakePoint($9, $10), 4326),
    $11,
    $12
)
RETURNING id
`

type CreateEstablishmentParams struct {
	Name      string      `json:"name"`
	Slug      string      `json:"slug"`
	Types     []string    `json:"types"`
	Email     string      `json:"email"`
	Website   string      `json:"website"`
	Timezone  string      `json:"timezone"`
	Phones    []byte      `json:"phones"`
	Address   []byte      `json:"address"`
	Lon       interface{} `json:"lon"`
	Lat       interface{} `json:"lat"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

func (q *Queries) CreateEstablishment(ctx context.Context, arg CreateEstablishmentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createEstablishment,
		arg.Name,
		arg.Slug,
		arg.Types,
		arg.Email,
		arg.Website,
		arg.Timezone,
		arg.Phones,
		arg.Address,
		arg.Lon,
		arg.Lat,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteEstablishment = `-- name: DeleteEstablishment :exec
DELETE FROM establishments
WHERE id = $1
`

func (q *Queries) DeleteEstablishment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEstablishment, id)
	return err
}

const getEstablishmentByID = `-- name: GetEstablishmentByID :one
SELECT
    id,
    name,
    slug,
    types,
    email,
    website,
    timezone,
    phones,
    address,
    ST_Y(location) AS lat,
    ST_X(location) AS lon,
    created_at,
    updated_at
FROM establishments
WHERE id = $1
`

type GetEstablishmentByIDRow struct {
	ID        uuid.UUID   `json:"id"`
	Name      string      `json:"name"`
	Slug      string      `json:"slug"`
	Types     []string    `json:"types"`
	Email     string      `json:"email"`
	Website   string      `json:"website"`
	Timezone  string      `json:"timezone"`
	Phones    []byte      `json:"phones"`
	Address   []byte      `json:"address"`
	Lat       interface{} `json:"lat"`
	Lon       interface{} `json:"lon"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

func (q *Queries) GetEstablishmentByID(ctx context.Context, id uuid.UUID) (GetEstablishmentByIDRow, error) {
	row := q.db.QueryRow(ctx, getEstablishmentByID, id)
	var i GetEstablishmentByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Types,
		&i.Email,
		&i.Website,
		&i.Timezone,
		&i.Phones,
		&i.Address,
		&i.Lat,
		&i.Lon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEstablishmentBySlug = `-- name: GetEstablishmentBySlug :one
SELECT
    id,
    name,
    slug,
    types,
    email,
    website,
    timezone,
    phones,
    address,
    CAST(ST_Y(location) AS double precision) AS lat,
    CAST(ST_X(location) AS double precision) AS lon,
    created_at,
    updated_at
FROM establishments
WHERE slug = $1
`

type GetEstablishmentBySlugRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	Types     []string  `json:"types"`
	Email     string    `json:"email"`
	Website   string    `json:"website"`
	Timezone  string    `json:"timezone"`
	Phones    []byte    `json:"phones"`
	Address   []byte    `json:"address"`
	Lat       float64   `json:"lat"`
	Lon       float64   `json:"lon"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) GetEstablishmentBySlug(ctx context.Context, slug string) (GetEstablishmentBySlugRow, error) {
	row := q.db.QueryRow(ctx, getEstablishmentBySlug, slug)
	var i GetEstablishmentBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Types,
		&i.Email,
		&i.Website,
		&i.Timezone,
		&i.Phones,
		&i.Address,
		&i.Lat,
		&i.Lon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
