// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgresdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Establishment struct {
	ID        pgtype.UUID
	Name      string
	Slug      string
	Types     []string
	Email     pgtype.Text
	Website   pgtype.Text
	Phones    []byte
	Location  interface{}
	Address   []byte
	Timezone  pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
