// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Establishment struct {
	ID        uuid.UUID   `json:"id"`
	Name      string      `json:"name"`
	Slug      string      `json:"slug"`
	Types     []string    `json:"types"`
	Email     string      `json:"email"`
	Website   string      `json:"website"`
	Timezone  string      `json:"timezone"`
	Phones    []byte      `json:"phones"`
	Address   []byte      `json:"address"`
	Location  interface{} `json:"location"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}
