// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Establishment struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	Types     []string
	Email     string
	Website   string
	Timezone  string
	Phones    []byte
	Address   []byte
	Location  interface{}
	CreatedAt time.Time
	UpdatedAt time.Time
}
