// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateEstablishment(ctx context.Context, arg CreateEstablishmentParams) (uuid.UUID, error)
	DeleteEstablishment(ctx context.Context, id uuid.UUID) error
	GetEstablishmentByID(ctx context.Context, id uuid.UUID) (GetEstablishmentByIDRow, error)
	GetEstablishmentBySlug(ctx context.Context, slug string) (GetEstablishmentBySlugRow, error)
	UpdateEstablishment(ctx context.Context, arg UpdateEstablishmentParams) error
}

var _ Querier = (*Queries)(nil)
